/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DistrictDTO } from '../models';
import { DistrictPagedResult } from '../models';
/**
 * DistrictApi - axios parameter creator
 * @export
 */
export const DistrictApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {boolean} [isActive] 
         * @param {boolean} [isArchive] 
         * @param {number} [offset] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDistrictGet: async (isActive?: boolean, isArchive?: boolean, offset?: number, count?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/district`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (isActive !== undefined) {
                localVarQueryParameter['IsActive'] = isActive;
            }

            if (isArchive !== undefined) {
                localVarQueryParameter['IsArchive'] = isArchive;
            }

            if (offset !== undefined) {
                localVarQueryParameter['Offset'] = offset;
            }

            if (count !== undefined) {
                localVarQueryParameter['Count'] = count;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDistrictIdGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiDistrictIdGet.');
            }
            const localVarPath = `/api/district/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DistrictApi - functional programming interface
 * @export
 */
export const DistrictApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {boolean} [isActive] 
         * @param {boolean} [isArchive] 
         * @param {number} [offset] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDistrictGet(isActive?: boolean, isArchive?: boolean, offset?: number, count?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DistrictPagedResult>>> {
            const localVarAxiosArgs = await DistrictApiAxiosParamCreator(configuration).apiDistrictGet(isActive, isArchive, offset, count, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDistrictIdGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DistrictDTO>>> {
            const localVarAxiosArgs = await DistrictApiAxiosParamCreator(configuration).apiDistrictIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DistrictApi - factory interface
 * @export
 */
export const DistrictApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {boolean} [isActive] 
         * @param {boolean} [isArchive] 
         * @param {number} [offset] 
         * @param {number} [count] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDistrictGet(isActive?: boolean, isArchive?: boolean, offset?: number, count?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<DistrictPagedResult>> {
            return DistrictApiFp(configuration).apiDistrictGet(isActive, isArchive, offset, count, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDistrictIdGet(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<DistrictDTO>> {
            return DistrictApiFp(configuration).apiDistrictIdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DistrictApi - object-oriented interface
 * @export
 * @class DistrictApi
 * @extends {BaseAPI}
 */
export class DistrictApi extends BaseAPI {
    /**
     * 
     * @param {boolean} [isActive] 
     * @param {boolean} [isArchive] 
     * @param {number} [offset] 
     * @param {number} [count] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DistrictApi
     */
    public async apiDistrictGet(isActive?: boolean, isArchive?: boolean, offset?: number, count?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<DistrictPagedResult>> {
        return DistrictApiFp(this.configuration).apiDistrictGet(isActive, isArchive, offset, count, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DistrictApi
     */
    public async apiDistrictIdGet(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<DistrictDTO>> {
        return DistrictApiFp(this.configuration).apiDistrictIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}
