/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface BusinessCategory
 */
export interface BusinessCategory {
  /**
   * @type {string}
   * @memberof BusinessCategory
   */
  uId?: number;
  categoryId?: string | null;

  /**
   * @type {string}
   * @memberof BusinessCategory
   */
  category?: string | null;

  /**
   * @type {string}
   * @memberof BusinessCategory
   */
  description?: string | null;
}

export type FormValuesPropsBusiness = {
  categoryId?: string;
  category?: string;
  description?: string;
};
