/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface City
 */
export interface City {
  /**
   * @type {number}
   * @memberof City
   */
  districtUId?: number;

  /**
   * @type {string}
   * @memberof City
   */

  name_en?: string | null;

  /**
   * @type {string}
   * @memberof City
   */
  nameSi?: string | null;

  /**
   * @type {string}
   * @memberof City
   */
  nameTa?: string | null;

  /**
   * @type {string}
   * @memberof City
   */
  postcode?: string | null;

  /**
   * @type {number}
   * @memberof City
   */
  latitude?: number;

  /**
   * @type {number}
   * @memberof City
   */
  longitude?: number;
}
