/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateUserCommand
 */
export interface CreateUserCommand {

    /**
     * @type {string}
     * @memberof CreateUserCommand
     */
    userId?: string | null;

    /**
     * @type {string}
     * @memberof CreateUserCommand
     */
    userName?: string | null;

    /**
     * @type {string}
     * @memberof CreateUserCommand
     */
    password?: string | null;

    /**
     * @type {string}
     * @memberof CreateUserCommand
     */
    email?: string | null;
}
