/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateOutletStatusCommand
 */
export interface CreateOutletStatusCommand {

    /**
     * @type {string}
     * @memberof CreateOutletStatusCommand
     */
    outletStatusID?: string | null;

    /**
     * @type {string}
     * @memberof CreateOutletStatusCommand
     */
    statusName?: string | null;

    /**
     * @type {string}
     * @memberof CreateOutletStatusCommand
     */
    description?: string | null;
}
