/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateProductGroupCommand
 */
export interface CreateProductGroupCommand {

    /**
     * @type {string}
     * @memberof CreateProductGroupCommand
     */
    productGroupId?: string | null;

    /**
     * @type {string}
     * @memberof CreateProductGroupCommand
     */
    productGroupName?: string | null;

    /**
     * @type {string}
     * @memberof CreateProductGroupCommand
     */
    description?: string | null;
}
