/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateDistributorCommand
 */
export interface CreateDistributorCommand {

    /**
     * @type {string}
     * @memberof CreateDistributorCommand
     */
    distributorID?: string | null;

    /**
     * @type {string}
     * @memberof CreateDistributorCommand
     */
    distributorName?: string | null;

    /**
     * @type {string}
     * @memberof CreateDistributorCommand
     */
    address?: string | null;

    /**
     * @type {number}
     * @memberof CreateDistributorCommand
     */
    provinceUId?: number;

    /**
     * @type {number}
     * @memberof CreateDistributorCommand
     */
    districtUId?: number;

    /**
     * @type {number}
     * @memberof CreateDistributorCommand
     */
    townUId?: number;

    /**
     * @type {string}
     * @memberof CreateDistributorCommand
     */
    phone?: string | null;

    /**
     * @type {number}
     * @memberof CreateDistributorCommand
     */
    titleUId?: number;

    /**
     * @type {string}
     * @memberof CreateDistributorCommand
     */
    ownerName?: string | null;

    /**
     * @type {string}
     * @memberof CreateDistributorCommand
     */
    ownerAddr?: string | null;

    /**
     * @type {string}
     * @memberof CreateDistributorCommand
     */
    ownerTpNo?: string | null;

    /**
     * @type {string}
     * @memberof CreateDistributorCommand
     */
    mobileNo?: string | null;

    /**
     * @type {Date}
     * @memberof CreateDistributorCommand
     */
    appointedDate?: Date;

    /**
     * @type {number}
     * @memberof CreateDistributorCommand
     */
    businessCategoryUId?: number;

    /**
     * @type {number}
     * @memberof CreateDistributorCommand
     */
    paymentTermUId?: number;
}
