/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateProductCommand
 */
export interface CreateProductCommand {

    /**
     * @type {string}
     * @memberof CreateProductCommand
     */
    productID?: string | null;

    /**
     * @type {string}
     * @memberof CreateProductCommand
     */
    productName?: string | null;

    /**
     * @type {string}
     * @memberof CreateProductCommand
     */
    description?: string | null;

    /**
     * @type {number}
     * @memberof CreateProductCommand
     */
    productGroupUId?: number;

    /**
     * @type {number}
     * @memberof CreateProductCommand
     */
    productCategoryUId?: number;

    /**
     * @type {boolean}
     * @memberof CreateProductCommand
     */
    isReturnable?: boolean;

    /**
     * @type {number}
     * @memberof CreateProductCommand
     */
    minOrderLevel?: number | null;

    /**
     * @type {number}
     * @memberof CreateProductCommand
     */
    maxOrderLevel?: number | null;

    /**
     * @type {number}
     * @memberof CreateProductCommand
     */
    qty?: number;

    /**
     * @type {number}
     * @memberof CreateProductCommand
     */
    uomuId?: number;

    /**
     * @type {string}
     * @memberof CreateProductCommand
     */
    barcodeID?: string | null;
}
