/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { City } from './city';
import { District } from './district';
import { OutletCategory } from './outlet-category';
import { OutletClassification } from './outlet-classification';
import { OutletStatus } from './outlet-status';
import { PaymentMode } from './payment-mode';
import { Province } from './province';
 /**
 * 
 *
 * @export
 * @interface OutletDTO
 */
export interface OutletDTO {

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    uId?: number;

    /**
     * @type {boolean}
     * @memberof OutletDTO
     */
    isArchive?: boolean;

    /**
     * @type {boolean}
     * @memberof OutletDTO
     */
    active?: boolean;

    /**
     * @type {Date}
     * @memberof OutletDTO
     */
    creationDate?: Date;

    /**
     * @type {Date}
     * @memberof OutletDTO
     */
    modifiedDate?: Date | null;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    totalRecordCount?: number;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    createdBy?: number;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    modifiedBy?: number;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    parentOutletCode?: string | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    outletID?: string | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    address?: string | null;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    provinceUId?: number;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    districtUId?: number;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    cityUId?: number;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    contactNo1?: string | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    contactNo2?: string | null;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    outletCategoryUId?: number;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    outletClassificationUId?: number;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    brNo?: string | null;

    /**
     * @type {boolean}
     * @memberof OutletDTO
     */
    isVat?: boolean | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    vatNo?: string | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    lat?: string | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    _long?: string | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    qrCode?: string | null;

    /**
     * @type {boolean}
     * @memberof OutletDTO
     */
    isExclusive?: boolean | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    exclusiveRemark?: string | null;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    outletStatusUId?: number;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    motherCompanyAddress?: string | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    ownerName?: string | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    ownerNIC?: string | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    ownerContactNo?: string | null;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    paymentModeUId?: number;

    /**
     * @type {boolean}
     * @memberof OutletDTO
     */
    isDiscountEligible?: boolean | null;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    creditLimit?: number | null;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    creditInvoiceLimit?: number | null;

    /**
     * @type {number}
     * @memberof OutletDTO
     */
    creditDays?: number | null;

    /**
     * @type {string}
     * @memberof OutletDTO
     */
    additionalNotes?: string | null;

    /**
     * @type {boolean}
     * @memberof OutletDTO
     */
    isAssetAvailable?: boolean | null;

    /**
     * @type {Province}
     * @memberof OutletDTO
     */
    province?: Province;

    /**
     * @type {District}
     * @memberof OutletDTO
     */
    district?: District;

    /**
     * @type {City}
     * @memberof OutletDTO
     */
    city?: City;

    /**
     * @type {OutletStatus}
     * @memberof OutletDTO
     */
    outletStatus?: OutletStatus;

    /**
     * @type {OutletClassification}
     * @memberof OutletDTO
     */
    outletClassification?: OutletClassification;

    /**
     * @type {OutletCategory}
     * @memberof OutletDTO
     */
    outletCategory?: OutletCategory;

    /**
     * @type {PaymentMode}
     * @memberof OutletDTO
     */
    paymentMode?: PaymentMode;
}
