/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface OutletCategory
 */
export interface OutletCategory {
  /**
   * @type {string}
   * @memberof OutletCategory
   */
  uId? : number;
  outletCategoryId?: string | null;

  /**
   * @type {string}
   * @memberof OutletCategory
   */
  outletCategoryName?: string | null;

  /**
   * @type {string}
   * @memberof OutletCategory
   */
  description?: string | null;
}

