/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface OutletStatus
 */
export interface OutletStatus {
  /**
   * @type {string}
   * @memberof OutletStatus
   */
  uId?: number;

  outletStatusID?: string | null;

  /**
   * @type {string}
   * @memberof OutletStatus
   */
  statusName?: string | null;

  /**
   * @type {string}
   * @memberof OutletStatus
   */
  description?: string | null;
}
