/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductGroup } from "./product-group";
import { ProductCategory } from "./product-category";
import { UOM } from "./uom";
/**
 *
 *
 * @export
 * @interface Product
 */
export interface Product {
  uId?: number;
  /**
   * @type {string}
   * @memberof Product
   */
  productID?: string | null;

  /**
   * @type {string}
   * @memberof Product
   */
  productName?: string | null;

  /**
   * @type {string}
   * @memberof Product
   */
  description?: string | null;

  /**
   * @type {number}
   * @memberof Product
   */
  productGroupUId?: number;
  productGroup: ProductGroup;
  /**
   * @type {number}
   * @memberof Product
   */
  productCategoryUId?: number;
  productCategory: ProductCategory;
  /**
   * @type {boolean}
   * @memberof Product
   */
  isReturnable?: boolean;

  /**
   * @type {number}
   * @memberof Product
   */
  minOrderLevel?: number | string | null;
  imgData?: any;
  /**
   * @type {number}
   * @memberof Product
   */
  maxOrderLevel?: number | string | null;

  /**
   * @type {number}
   * @memberof Product
   */
  qty?: number | string | null;

  /**
   * @type {number}
   * @memberof Product
   */
  uomuId?: number;
  uom: UOM;
  /**
   * @type {string}
   * @memberof Product
   */
  barcodeID?: string | null;
}
export type ProductFormValuesProps = {
  productID?: string | null;
  productName?: string | null;
  description?: string | null;
  productGroupUId?: number | string | null;
  productGroup?: string | null;
  productCategoryUId?: number | string | null;
  productCategory?: string | null;
  uomuId?: number | string | null;
  uom?: string | null;
  imgData?: any;
  isReturnable?: boolean;
  minOrderLevel?: number | string | null;
  maxOrderLevel?: number | string | null;
  qty?: number | string | null;
  barcodeID?: string | null;
  salesUnitTypeAssignmentUIds?: number[] | null;
  salesUnitTypeAssignmentDefaultUId?: number | null | undefined;
};
