/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProductCategoryAudit
 */
export interface ProductCategoryAudit {

    /**
     * @type {number}
     * @memberof ProductCategoryAudit
     */
    auditID?: number;

    /**
     * @type {number}
     * @memberof ProductCategoryAudit
     */
    uId?: number;

    /**
     * @type {string}
     * @memberof ProductCategoryAudit
     */
    action?: string | null;

    /**
     * @type {Date}
     * @memberof ProductCategoryAudit
     */
    auditDate?: Date;

    /**
     * @type {Date}
     * @memberof ProductCategoryAudit
     */
    creationDate?: Date;

    /**
     * @type {Date}
     * @memberof ProductCategoryAudit
     */
    modifiedDate?: Date | null;

    /**
     * @type {number}
     * @memberof ProductCategoryAudit
     */
    createdBy?: number;

    /**
     * @type {number}
     * @memberof ProductCategoryAudit
     */
    modifiedBy?: number;

    /**
     * @type {boolean}
     * @memberof ProductCategoryAudit
     */
    active?: boolean;

    /**
     * @type {boolean}
     * @memberof ProductCategoryAudit
     */
    isArchive?: boolean;

    /**
     * @type {number}
     * @memberof ProductCategoryAudit
     */
    totalRecordCount?: number;

    /**
     * @type {string}
     * @memberof ProductCategoryAudit
     */
    auditUser?: string | null;

    /**
     * @type {string}
     * @memberof ProductCategoryAudit
     */
    categoryId?: string | null;

    /**
     * @type {string}
     * @memberof ProductCategoryAudit
     */
    categoryName?: string | null;

    /**
     * @type {string}
     * @memberof ProductCategoryAudit
     */
    description?: string | null;
}
