/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Province
 */
export interface Province {

    /**
     * @type {string}
     * @memberof Province
     */
    nameEN?: string | null;

    /**
     * @type {string}
     * @memberof Province
     */
    nameSI?: string | null;

    /**
     * @type {string}
     * @memberof Province
     */
    nameTA?: string | null;
}
