/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateRouteCommand
 */
export interface UpdateRouteCommand {

    /**
     * @type {string}
     * @memberof UpdateRouteCommand
     */
    routeId?: string | null;

    /**
     * @type {string}
     * @memberof UpdateRouteCommand
     */
    routeName?: string | null;

    /**
     * @type {string}
     * @memberof UpdateRouteCommand
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof UpdateRouteCommand
     */
    startPoint?: string | null;

    /**
     * @type {string}
     * @memberof UpdateRouteCommand
     */
    endPoint?: string | null;

    /**
     * @type {number}
     * @memberof UpdateRouteCommand
     */
    distance?: number;

    /**
     * @type {number}
     * @memberof UpdateRouteCommand
     */
    estimateTime?: number;
}
