/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateOutletCommand
 */
export interface UpdateOutletCommand {

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    parentOutletCode?: string | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    outletID?: string | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    address?: string | null;

    /**
     * @type {number}
     * @memberof UpdateOutletCommand
     */
    provinceUId?: number;

    /**
     * @type {number}
     * @memberof UpdateOutletCommand
     */
    districtUId?: number;

    /**
     * @type {number}
     * @memberof UpdateOutletCommand
     */
    cityUId?: number;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    contactNo1?: string | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    contactNo2?: string | null;

    /**
     * @type {number}
     * @memberof UpdateOutletCommand
     */
    outletCategoryUId?: number;

    /**
     * @type {number}
     * @memberof UpdateOutletCommand
     */
    outletClassificationUId?: number;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    brNo?: string | null;

    /**
     * @type {boolean}
     * @memberof UpdateOutletCommand
     */
    isVat?: boolean | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    vatNo?: string | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    lat?: string | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    _long?: string | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    qrCode?: string | null;

    /**
     * @type {boolean}
     * @memberof UpdateOutletCommand
     */
    isExclusive?: boolean | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    exclusiveRemark?: string | null;

    /**
     * @type {number}
     * @memberof UpdateOutletCommand
     */
    outletStatusUId?: number;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    motherCompanyAddress?: string | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    ownerName?: string | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    ownerNIC?: string | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    ownerContactNo?: string | null;

    /**
     * @type {number}
     * @memberof UpdateOutletCommand
     */
    paymentModeUId?: number;

    /**
     * @type {boolean}
     * @memberof UpdateOutletCommand
     */
    isDiscountEligible?: boolean | null;

    /**
     * @type {number}
     * @memberof UpdateOutletCommand
     */
    creditLimit?: number | null;

    /**
     * @type {number}
     * @memberof UpdateOutletCommand
     */
    creditInvoiceLimit?: number | null;

    /**
     * @type {number}
     * @memberof UpdateOutletCommand
     */
    creditDays?: number | null;

    /**
     * @type {string}
     * @memberof UpdateOutletCommand
     */
    additionalNotes?: string | null;

    /**
     * @type {boolean}
     * @memberof UpdateOutletCommand
     */
    isAssetAvailable?: boolean | null;
}
