/* tslint:disable */
/* eslint-disable */
/**
 * SFAWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BusinessCategory } from './business-category';
 /**
 * 
 *
 * @export
 * @interface UpdateBusinessCategoryCommand
 */
export interface UpdateBusinessCategoryCommand {

    /**
     * @type {BusinessCategory}
     * @memberof UpdateBusinessCategoryCommand
     */
    businessCategory?: BusinessCategory;
}
