import { StyleSheet } from "@react-pdf/renderer";

export const PrintInvoiceStyles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, fontFamily: "Helvetica" },
  header: {
    fontSize: 20,
    textAlign: "center",
    marginBottom: 16,
    fontWeight: "bold",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  col: { flexDirection: "column", flexGrow: 1 },
  section: { marginBottom: 16 },
  table: {
    width: "100%",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    marginTop: 8,
  },
  title: {
    fontSize: 10,
    textAlign: "left",
    fontWeight: "bold",
  },
  tableRow: { flexDirection: "row" },
  tableCol: {
    width: "14.28%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColDiscount: {
    width: "28.56%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableColReturn: {
    width: "16.66%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableCell: {
    marginLeft: 1.5,
    marginTop: 3,
    marginBottom: 3,
    fontSize: 9,
  },
  tableCellRight: {
    textAlign: "right",
    marginRight: 1.5,
    marginTop: 3,
    marginBottom: 3,
    fontSize: 9,
  },
  tableCellHeader: {
    paddingLeft: 3,
    paddingRight: 3,
    paddingTop: 3,
    paddingBottom: 3,
    fontSize: 9,
    fontWeight: "bold",
    // backgroundColor: "#C4D9FF",
  },
  tableCellHeaderRight: {
    textAlign: "right",
    paddingLeft: 3,
    paddingRight: 3,
    paddingTop: 3,
    paddingBottom: 3,
    fontSize: 9,
    fontWeight: "bold",
    // backgroundColor: "#C4D9FF",
  },
  tableCellHeaderTotal: {
    textAlign: "right",
    paddingLeft: 3,
    paddingRight: 3,
    paddingTop: 3,
    paddingBottom: 3,
    fontSize: 9,
    fontWeight: "bold",
    backgroundColor: "#e9e9e9",
  },
  summary: {
    marginTop: 16,
    marginLeft: "auto",
    width: 200,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  summaryLabel: {
    fontWeight: "bold",
  },
  summaryValue: {
    textAlign: "right",
    minWidth: 60,
    flex: 1,
  },
  payment: {
    marginTop: 16,
    marginBottom: 16,
  },
  footer: {
    marginTop: 0,
    textAlign: "center",
    fontSize: 10,
    color: "#888",
  },
  footerBox: {
    // backgroundColor: "#EAF6FF",
    padding: 8,
    borderRadius: 4,
    marginTop: 24,
    marginBottom: 0,
    textAlign: "center",
  },
  hr: {
    borderBottomWidth: 1,
    borderBottomColor: "#bbb",
    borderBottomStyle: "solid",
    marginTop: 16,
    marginBottom: 8,
    width: "100%",
  },
  hrLine: {
    borderBottomWidth: 1,
    borderBottomColor: "#bbb",
    borderBottomStyle: "solid",
    marginTop: 2,
    marginBottom: 8,
    width: "100%",
  },
  hrHeader: {
    borderBottomWidth: 1,
    borderBottomColor: "#000000",
    borderBottomStyle: "solid",
    marginTop: 0,
    marginBottom: 10,
    width: "100%",
  },
  hrFooter: {
    borderBottomWidth: 1,
    borderBottomColor: "#000000",
    borderBottomStyle: "solid",
    marginTop: 32,
    marginBottom: 0,
    width: "100%",
  },
  discountSubtotalRow: {
    backgroundColor: "#EAF6FF",
  },
  salesSubtotalColspan: {
    width: "57.12%", // 14.28% * 4
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    justifyContent: "center",
    backgroundColor: "#EAF6FF",
  },
  discountSubtotalColspan: {
    width: "57.12%", // 28.56% * 2
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    justifyContent: "center",
  },
  returnSubtotalColspan: {
    width: "66.64%", // 16.66% * 4
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    justifyContent: "center",
    backgroundColor: "#EAF6FF",
  },
  discountSubtotalText: {
    textAlign: "center",
  },
});
